site_name: Jacob | Студенческий бот
repo_url: https://github.com/dadyarri/jacob
repo_name: dadyarri/jacob
edit_uri: ""
copyright: Copyright &copy; 2019 - 2020 Даниил Голубев
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
  - awesome-pages:
      collapse_single_pages: true
markdown_extensions:
  - admonition
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
  font:
    code: Fira Code
  language: ru
  logo: assets/logo/jacob.svg
  favicon: assets/logo/jacob.svg
  features:
    - instant
    - tabs
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/vk
      link: https://vk.com/jacob_bot
      name: Страница бота в ВК
    - icon: fontawesome/brands/telegram
      link: https://t.me/dadyarri
      name: Связь с автором

nav:
  - Главная: index.md
  - Возможности:
      - Призыв: functions/call.md
      - Финансы: functions/finances.md
      - Настройки: functions/settings.md
  - Настройка:
      - Создание группы: configure/mkgroup.md
      - Настройка бота: configure/bot.md
      - Добавление бота в чаты: configure/chats.md

